twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig'] # accepte plusieurs th√®mes
    globals: 
        app_name: 'Gaboma Annonce'
        locales: '%app.locales%'
        navs: '@App\Twig\NavExtension'
        site: 
            name: 'Gaboma annonce'
            description: 'Site annonce'
            email: 'leseoya@gmail.com'
            current_name: 'F cfa'
            current: 'XOF'
            phone_number_1: '+221 78 127 82 88'
            phone_number_2: '+221 77 000 00 00'
            link: "https://gaboma-annonce.com"
            user_empty: 'empty.png'
when@test:
    twig:
        strict_variables: true
